// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myydsaeielkpealyujpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eWRzYWVpZWxrcGVhbHl1anBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzk5MDAsImV4cCI6MjA2MTY1NTkwMH0.dFsB2DsFUY_cRhXdspiAVwHXdjRQr56NXHtZVCmZ1Cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);